### ISSUE TITLE
Не хватает пропатченного ядра paper 1.12.2

### ISSUE THREAD

**Issue by andllillmon** [KeeperJerry/LauncherSchool#10]
Не хватает пропатченного ядра paper 1.12.2, прошу добавить данную версию тк она более производительна по сравнению со spigot. Возможно за небольшую оплату или подсказать как можно пропатчить.

**Comment by xstmass** [comment]
Во-первых, такие вопросы не касаются работы лаунчера и им не место в его ишшуях. Во-вторых, для таких вопросов есть дискорд автора форка. В-третьих, его патчить уже не нужно.

**Comment by andllillmon** [comment]
Теперь могу писать в дискорде, закрываю
